-- MySQL Script generated by MySQL Workbench
-- mié 23 nov 2022 10:50:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_aergibide
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_aergibide
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_aergibide` ;
USE `db_aergibide` ;

CREATE USER 'ikasdev'@'%' IDENTIFIED BY 'ACai7925';
GRANT ALL PRIVILEGES ON db_aergibide.* TO 'ikasdev'@'%';

-- -----------------------------------------------------
-- Table `db_aergibide`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`empleado` (
  `numEmple` INT NOT NULL,
  `nombre` VARCHAR(60) NULL,
  `apellidos` VARCHAR(100) NULL,
  `pass` VARCHAR(4500) NOT NULL,
  `correo` VARCHAR(100) NULL,
  `departamento` VARCHAR(6) NULL,
  PRIMARY KEY (`numEmple`),
  UNIQUE INDEX `Correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`pregunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(60) NULL,
  `contenido` VARCHAR(4500) NULL,
  `fecha` DATE NULL,
  `tags` VARCHAR(100) NULL,
  `empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pregunta_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Pregunta_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`respuesta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(4500) NULL,
  `empleado_numEmple` INT NOT NULL,
  `id_pregunta` INT NOT NULL,
  PRIMARY KEY (`id`, `id_pregunta`),
  INDEX `fk_Respuesta_Empleado_idx` (`empleado_numEmple` ASC) VISIBLE,
  INDEX `fk_Respuesta_Pregunta1_idx` (`id_pregunta` ASC) VISIBLE,
  CONSTRAINT `fk_Respuesta_Empleado`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respuesta_Pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `db_aergibide`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`guia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(4500) NULL,
  `empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Guia_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Guia_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`tutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`tutorial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(4500) NULL,
  `empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tutorial_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Tutorial_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`notificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_numEmple` INT NOT NULL,
  `titulo` VARCHAR(4500) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Notificacion_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`favorito` (
  `empleado_numEmple` INT NOT NULL,
  `pregunta_ID` INT NOT NULL,
  PRIMARY KEY (`empleado_numEmple`, `pregunta_ID`),
  INDEX `fk_Empleado_has_Pregunta_Pregunta1_idx` (`pregunta_ID` ASC) VISIBLE,
  INDEX `fk_Empleado_has_Pregunta_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_has_Pregunta_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Pregunta_Pregunta1`
    FOREIGN KEY (`pregunta_ID`)
    REFERENCES `db_aergibide`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`archivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `ruta` VARCHAR(100) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`archivo_respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`archivo_respuesta` (
  `id` INT NOT NULL,
  `id_archivo` INT NOT NULL,
  `id_respuesta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_archivo_respuesta_archivo1_idx` (`id_archivo` ASC) VISIBLE,
  INDEX `fk_archivo_respuesta_Respuesta1_idx` (`id_respuesta` ASC) VISIBLE,
  CONSTRAINT `fk_archivo_respuesta_archivo1`
    FOREIGN KEY (`id_archivo`)
    REFERENCES `db_aergibide`.`archivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivo_respuesta_Respuesta1`
    FOREIGN KEY (`id_respuesta`)
    REFERENCES `db_aergibide`.`respuesta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
