-- MySQL Script generated by MySQL Workbench
-- mar 22 nov 2022 12:28:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_aergibide
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_aergibide
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_aergibide` ;
USE `db_aergibide` ;

-- -----------------------------------------------------
-- Table `db_aergibide`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`Empleado` (
  `Num_Empl` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Contrasenia` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`Num_Empl`),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`Pregunta` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(4500) NULL,
  `Contenido` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `Tags` VARCHAR(45) NULL,
  `Empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Pregunta_Empleado1_idx` (`Empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Pregunta_Empleado1`
    FOREIGN KEY (`Empleado_numEmple`)
    REFERENCES `db_aergibide`.`Empleado` (`Num_Empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`Respuesta` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(4500) NULL,
  `Empleado_numEmple` INT NOT NULL,
  `Pregunta_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Pregunta_ID`),
  INDEX `fk_Respuesta_Empleado_idx` (`Empleado_numEmple` ASC) VISIBLE,
  INDEX `fk_Respuesta_Pregunta1_idx` (`Pregunta_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Respuesta_Empleado`
    FOREIGN KEY (`Empleado_numEmple`)
    REFERENCES `db_aergibide`.`Empleado` (`Num_Empl`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respuesta_Pregunta1`
    FOREIGN KEY (`Pregunta_ID`)
    REFERENCES `db_aergibide`.`Pregunta` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`Guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`Guia` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(4500) NULL,
  `Empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Guia_Empleado1_idx` (`Empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Guia_Empleado1`
    FOREIGN KEY (`Empleado_numEmple`)
    REFERENCES `db_aergibide`.`Empleado` (`Num_Empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`Tutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`Tutorial` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(4500) NULL,
  `Empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Tutorial_Empleado1_idx` (`Empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Tutorial_Empleado1`
    FOREIGN KEY (`Empleado_numEmple`)
    REFERENCES `db_aergibide`.`Empleado` (`Num_Empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`Notificacion` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Empleado_numEmple` INT NOT NULL,
  `Titulo` VARCHAR(4500) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Notificacion_Empleado1_idx` (`Empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Empleado1`
    FOREIGN KEY (`Empleado_numEmple`)
    REFERENCES `db_aergibide`.`Empleado` (`Num_Empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`Favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`Favorito` (
  `Empleado_numEmple` INT NOT NULL,
  `Pregunta_ID` INT NOT NULL,
  PRIMARY KEY (`Empleado_numEmple`, `Pregunta_ID`),
  INDEX `fk_Empleado_has_Pregunta_Pregunta1_idx` (`Pregunta_ID` ASC) VISIBLE,
  INDEX `fk_Empleado_has_Pregunta_Empleado1_idx` (`Empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_has_Pregunta_Empleado1`
    FOREIGN KEY (`Empleado_numEmple`)
    REFERENCES `db_aergibide`.`Empleado` (`Num_Empl`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Pregunta_Pregunta1`
    FOREIGN KEY (`Pregunta_ID`)
    REFERENCES `db_aergibide`.`Pregunta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
