-- MySQL Script generated by MySQL Workbench
-- mié 23 nov 2022 08:42:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reto2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reto2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reto2` ;
USE `reto2` ;

-- -----------------------------------------------------
-- Table `reto2`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Empleado` (
  `numEmple` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Contrasenia` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`numEmple`),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Pregunta` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL,
  `Contenido` VARCHAR(45) NULL,
  `Fecha` VARCHAR(45) NULL,
  `Tags` VARCHAR(45) NULL,
  `empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Pregunta_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Pregunta_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `reto2`.`Empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Respuesta` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(45) NULL,
  `empleado_numEmple` INT NOT NULL,
  `id_pregunta` INT NOT NULL,
  PRIMARY KEY (`ID`, `id_pregunta`),
  INDEX `fk_Respuesta_Empleado_idx` (`empleado_numEmple` ASC) VISIBLE,
  INDEX `fk_Respuesta_Pregunta1_idx` (`id_pregunta` ASC) VISIBLE,
  CONSTRAINT `fk_Respuesta_Empleado`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `reto2`.`Empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respuesta_Pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `reto2`.`Pregunta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Guia` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(45) NULL,
  `empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Guia_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Guia_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `reto2`.`Empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Tutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Tutorial` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(45) NULL,
  `empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Tutorial_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Tutorial_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `reto2`.`Empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Notificacion` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `empleado_numEmple` INT NOT NULL,
  `titulo` VARCHAR(4500) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Notificacion_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `reto2`.`Empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Favorito` (
  `empleado_numEmple` INT NOT NULL,
  `Pregunta_ID` INT NOT NULL,
  PRIMARY KEY (`empleado_numEmple`, `Pregunta_ID`),
  INDEX `fk_Empleado_has_Pregunta_Pregunta1_idx` (`Pregunta_ID` ASC) VISIBLE,
  INDEX `fk_Empleado_has_Pregunta_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_has_Pregunta_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `reto2`.`Empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Pregunta_Pregunta1`
    FOREIGN KEY (`Pregunta_ID`)
    REFERENCES `reto2`.`Pregunta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`archivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `ruta` VARCHAR(100) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`archivo_respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`archivo_respuesta` (
  `id` INT NOT NULL,
  `id_archivo` INT NOT NULL,
  `id_respuesta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_archivo_respuesta_archivo1_idx` (`id_archivo` ASC) VISIBLE,
  INDEX `fk_archivo_respuesta_Respuesta1_idx` (`id_respuesta` ASC) VISIBLE,
  CONSTRAINT `fk_archivo_respuesta_archivo1`
    FOREIGN KEY (`id_archivo`)
    REFERENCES `reto2`.`archivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivo_respuesta_Respuesta1`
    FOREIGN KEY (`id_respuesta`)
    REFERENCES `reto2`.`Respuesta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
