-- MySQL Script generated by MySQL Workbench
-- vie 11 nov 2022 08:43:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_aergibide
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Crear usuario
-- -----------------------------------------------------
CREATE USER 'ikasdev'@'%' IDENTIFIED BY 'ACai7925';
GRANT ALL PRIVILEGES ON db_aergibide.* TO 'ikasdev'@'%';
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Schema db_aergibide
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_aergibide` ;
USE `db_aergibide` ;

-- -----------------------------------------------------
-- Table `db_aergibide`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`empleado` (
  `numEmple` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `pass` VARCHAR(350) NOT NULL,
  `correo` VARCHAR(60) NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`numEmple`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`pregunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `contenido` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `tags` VARCHAR(45) NULL,
  `empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pregunta_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Pregunta_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`respuesta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(20) NOT NULL,
  `contenido` VARCHAR(45) NULL,
  `empleado_numEmple` INT NOT NULL,
  `pregunta_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pregunta_id`),
  INDEX `fk_Respuesta_Empleado_idx` (`empleado_numEmple` ASC) VISIBLE,
  INDEX `fk_Respuesta_Pregunta1_idx` (`pregunta_id` ASC) VISIBLE,
  CONSTRAINT `fk_Respuesta_Empleado`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respuesta_Pregunta1`
    FOREIGN KEY (`pregunta_id`)
    REFERENCES `db_aergibide`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`guia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(45) NULL,
  `empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Guia_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Guia_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`tutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`tutorial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(45) NULL,
  `empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tutorial_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Tutorial_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`notificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(20) NOT NULL,
  `empleado_numEmple` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Notificacion_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `fk_Notificacion_Titulo1_idx` (`titulo` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Titulo1`
    FOREIGN KEY (`titulo`)
    REFERENCES `db_aergibide`.`respuesta` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_aergibide`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_aergibide`.`favorito` (
  `empleado_numEmple` INT NOT NULL,
  `pregunta_id` INT NOT NULL,
  PRIMARY KEY (`empleado_numEmple`, `pregunta_id`),
  INDEX `fk_Empleado_has_Pregunta_Pregunta1_idx` (`pregunta_id` ASC) VISIBLE,
  INDEX `fk_Empleado_has_Pregunta_Empleado1_idx` (`empleado_numEmple` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_has_Pregunta_Empleado1`
    FOREIGN KEY (`empleado_numEmple`)
    REFERENCES `db_aergibide`.`empleado` (`numEmple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Pregunta_Pregunta1`
    FOREIGN KEY (`pregunta_id`)
    REFERENCES `db_aergibide`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
