-- MySQL Script generated by MySQL Workbench
-- mié 09 nov 2022 10:55:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Crear usuario

CREATE USER 'ikasdev'@'%' IDENTIFIED BY 'AIac7925';

GRANT ALL PRIVILEGES ON reto2.* TO 'ikasdev'@'%';

FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Schema reto2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reto2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reto2` ;
USE `reto2` ;

-- -----------------------------------------------------
-- Table `reto2`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Empleado` (
  `Num_Empl` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`Num_Empl`),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Respuesta` (
  `ID` INT NOT NULL,
  `Contenido` VARCHAR(45) NULL,
  `Empleado_Num_Empl` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Respuesta_Empleado_idx` (`Empleado_Num_Empl` ASC) VISIBLE,
  CONSTRAINT `fk_Respuesta_Empleado`
    FOREIGN KEY (`Empleado_Num_Empl`)
    REFERENCES `reto2`.`Empleado` (`Num_Empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Pregunta` (
  `ID` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Contenido` VARCHAR(45) NULL,
  `Fecha` VARCHAR(45) NULL,
  `Tags` VARCHAR(45) NULL,
  `Empleado_Num_Empl` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Pregunta_Empleado1_idx` (`Empleado_Num_Empl` ASC) VISIBLE,
  CONSTRAINT `fk_Pregunta_Empleado1`
    FOREIGN KEY (`Empleado_Num_Empl`)
    REFERENCES `reto2`.`Empleado` (`Num_Empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Sesion` (
  `ID` INT NOT NULL,
  `Contrasenia` VARCHAR(45) NULL,
  `Empleado_Num_Empl` INT NOT NULL,
  PRIMARY KEY (`ID`, `Empleado_Num_Empl`),
  INDEX `fk_Sesion_Empleado1_idx` (`Empleado_Num_Empl` ASC) VISIBLE,
  CONSTRAINT `fk_Sesion_Empleado1`
    FOREIGN KEY (`Empleado_Num_Empl`)
    REFERENCES `reto2`.`Empleado` (`Num_Empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Guia` (
  `ID` INT NOT NULL,
  `Contenido` VARCHAR(45) NULL,
  `Empleado_Num_Empl` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Guia_Empleado1_idx` (`Empleado_Num_Empl` ASC) VISIBLE,
  CONSTRAINT `fk_Guia_Empleado1`
    FOREIGN KEY (`Empleado_Num_Empl`)
    REFERENCES `reto2`.`Empleado` (`Num_Empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Tutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Tutorial` (
  `ID` INT NOT NULL,
  `Contenido` VARCHAR(45) NULL,
  `Empleado_Num_Empl` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Tutorial_Empleado1_idx` (`Empleado_Num_Empl` ASC) VISIBLE,
  CONSTRAINT `fk_Tutorial_Empleado1`
    FOREIGN KEY (`Empleado_Num_Empl`)
    REFERENCES `reto2`.`Empleado` (`Num_Empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reto2`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto2`.`Notificacion` (
  `ID` INT NOT NULL,
  `Empleado_Num_Empl` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Notificacion_Empleado1_idx` (`Empleado_Num_Empl` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Empleado1`
    FOREIGN KEY (`Empleado_Num_Empl`)
    REFERENCES `reto2`.`Empleado` (`Num_Empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
